name: Build and Deploy to GitHub Registry

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        id: checkout
        uses: actions/checkout@v4

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_OUTPUT"

      - name: Validate Semver
        id: semver
        uses: matt-usurp/validate-semver@v2
        with:
          version: ${{ steps.get_version.outputs.VERSION }}

      - name: Log in to the Container registry
        id: login_registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build_and_push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.VERSION }}
          build-args: |
            GEMINI_CLI_VERSION=${{ steps.get_version.outputs.VERSION }}
